services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"  
    environment:
      - DATABASE_URL=postgresql://locadora_user:password@postgres:5432/locadora_db
    depends_on:
      - postgres
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: locadora_db
      POSTGRES_USER: locadora_user  
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: